name: CI Zero Trust (OIDC + No Secrets)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write     # üëà OIDC b·∫Øt bu·ªôc
  contents: read

env:
  AWS_REGION: us-east-2
  ECR_REPO: my-app
  APP_NAME: my-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1Ô∏è‚É£ Checkout source
    - name: Checkout
      uses: actions/checkout@v4

    # 2Ô∏è‚É£ Assume IAM Role via OIDC (NO AWS KEY)
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::782017371887:role/github-ci-role
        aws-region: ${{ env.AWS_REGION }}

    # 3Ô∏è‚É£ Login ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # 4Ô∏è‚É£ Build Docker image (KH√îNG .env)
    - name: Build image
      run: |
          cd app-demo/backend
          docker build -t $ECR_REPO:${{ github.sha }} .

    # 5Ô∏è‚É£ Tag image
    - name: Tag image
      run: |
        docker tag $ECR_REPO:${{ github.sha }} \
        782017371887.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:${{ github.sha }}

    # 6Ô∏è‚É£ Push image
    - name: Push image to ECR
      run: |
        docker push \
        782017371887.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:${{ github.sha }}

    # # 7Ô∏è‚É£ Update deployment definition (KH√îNG SECRET)
    # - name: Update launch template / manifest
    #   run: |
    #     sed -i "s|IMAGE_TAG|${{ github.sha }}|g" deploy/app.yaml

    # # 8Ô∏è‚É£ Commit manifest (GitOps-style)
    # - name: Commit deployment change
    #   run: |
    #     git config user.name "ci-bot"
    #     git config user.email "ci@company.com"
    #     git commit -am "Deploy image ${{ github.sha }}"
    #     git push
